runtime: python
env: flex
entrypoint: gunicorn -b :$PORT --timeout 100 main:app
service: fledge
runtime_config:
  python_version: 3

resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 15

        



