env: flex
runtime: custom
env_variables:
    GOOGLE_APPLICATION_CREDENTIALS: "/key.json"

entrypoint: python main.py

runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10




    
        



